services:
  - type: web
    name: oscar-converter
    env: python
    buildCommand: pip install -r requirements_deploy.txt
    startCommand: gunicorn -w 2 -b 0.0.0.0:$PORT oscar_web_production:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
